config/routes.rb
Rails.application.routes.draw do
  get '/welcome/:first_name', to: 'dynamic#welcome'
  get '/static/home'
  get 'static/contact'
  get 'static/team'
  get '/homy', to: 'homy#homy_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, :as => :likeable, dependent: :destroy
  has_many :comments, :as => :commentable, dependent: :destroy
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments, :as => :commentable, dependent: :destroy
  has_many :join_table_gossip_tags 
  has_many :tags, through: :join_table_gossip_tags
  has_many :likes, :as => :likeable, dependent: :destroy
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/join_table_message_recipient.rb
class JoinTableMessageRecipient < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :private_message
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_table_message_recipients
  has_many :recipients, class_name: "User", through: :join_table_message_recipients
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :join_table_message_recipients
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "JoinTableMessageRecipient"
  has_many :likes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_controller.rb
class DynamicController < ApplicationController
  def welcome
    @first_name = params[:first_name]
  end
end

app/controllers/homy_controller.rb
class HomyController < ApplicationController
  def homy_page
    @gossips = Gossip.all
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def contact
  end

  def team
  end

  def homy_page
    @gossips = Gossip.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamic_helper.rb
module DynamicHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/dynamic/welcome.html.erb
<head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <a class="nav-link" <%= link_to "Home", static_home_path %> <span class="sr-only">(current)</span></a>

      </li>
      <li class="nav-item">
        <a class="nav-link" <a class="nav-link" <%= link_to "contact", static_contact_path %> 
      </li>
      
      <li class="nav-item">
        <a class="nav-link" <a class="nav-link" <%= link_to "team", static_team_path %> 
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

</head>


<h3>BIENVENUE <%= @first_name %> ! Ici c'est notre super site de potins, il est chouette, non ?</h3>

app/views/homy/homy_page.html.erb
<html>

</head>
<h1>Bienvenue à toi!</h1>

<p>Voici la liste des potins créés: </p>
<div class="container">
<div class="row">
    <% @gossips.each do |gossip| %>
        <div class="col-lg-3 col-md-6 col-xs-12 between_cards">
            <div class="box-part text-center cards-gossip">
                <div class="card text-white bg-dark">
                    <div class="card-body card-home">
                        <h5 class="card-title"><%= gossip.title %></h5>
                        <h6 class="card-subtitle mb-2 text-muted">Auteur : <%= gossip.user %> </h6>
                        <p class="card-text"><%= gossip.comments.length %> commentaires</p>
                    </div>
                </div>
            </div>
        </div>
    <% end %>	
</div>		
</div>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">   
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  
    <title>Thegossipproject190805</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>